spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true # Enable Eureka discovery
    gateway:
      routes:
        - id: r1 # Route for client-service
          uri: lb://client-service # Dynamic URI using service discovery
          predicates:
            - Path=/client/** # Route requests starting with /client

        - id: r2 # Route for voiture-service
          uri: lb://voiture-service # Dynamic URI using service discovery
          predicates:
            - Path=/voitures/**,/voiture/** # Route requests starting with /voitures or /voiture

server:
  port: 8888 # Port for the Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka server URL
  instance:
    hostname: localhost