spring:
  application:
    name: voiture-service
  cloud:
    discovery:
      enabled: true

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

